In [2]:
import pandas as pd
q1_df = pd.read_csv('../311q1.csv')
q2_df = pd.read_csv('../311q2.csv')
q3_df = pd.read_csv('../311q3.csv')
q4_df = pd.read_csv('../311q4.csv')

/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:2785: DtypeWarning: Columns (17) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [3]:
df = pd.concat([q1_df, q2_df, q3_df, q4_df])

In [4]:
df.head()

,Unique Key,Created Date,Closed Date,Agency,Agency Name,Complaint Type,Descriptor,Location Type,Incident Zip,Incident Address,...,Vehicle Type,Taxi Company Borough,Taxi Pick Up Location,Bridge Highway Name,Bridge Highway Direction,Road Ramp,Bridge Highway Segment,Latitude,Longitude,Location
0,32305299,01/01/2016 12:00:09 AM,01/01/2016 01:57:32 AM,NYPD,New York City Police Department,Noise - Street/Sidewalk,Loud Music/Party,Street/Sidewalk,11201.0,102 GOLD STREET,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.701823,-73.982840,"(40.70182309943841, -73.98284003196223)"
1,32310343,01/01/2016 12:00:40 AM,01/01/2016 03:12:53 AM,NYPD,New York City Police Department,Noise - Residential,Loud Music/Party,Residential Building/House,10468.0,3155 GRAND CONCOURSE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.875565,-73.886111,"(40.87556453341452, -73.88611123391182)"
2,32309107,01/01/2016 12:01:09 AM,01/21/2016 09:20:55 AM,HPD,Department of Housing Preservation and Develop...,ELECTRIC,NO LIGHTING,RESIDENTIAL BUILDING,10467.0,3572 DEKALB AVENUE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.884277,-73.878885,"(40.8842770627239, -73.87888510394457)"
3,32308578,01/01/2016 12:02:59 AM,01/01/2016 11:35:50 PM,NYPD,New York City Police Department,Noise - Residential,Loud Music/Party,Residential Building/House,NaN,539 SIXTH AVENUE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,32309212,01/01/2016 12:03:03 AM,01/08/2016 01:13:00 AM,HPD,Department of Housing Preservation and Develop...,HEAT/HOT WATER,ENTIRE BUILDING,RESIDENTIAL BUILDING,10458.0,2345 TIEBOUT AVENUE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.857841,-73.896607,"(40.85784092074736, -73.8966070485658)"

In [5]:
df.head

(1930445, 41)

In [6]:
dfs = df.sample(frac=.01)

In [10]:
dfs.to_csv('subsample.csv')

In [7]:
dfs.shape

(19304, 41)

In [9]:
dfs

,Unique Key,Created Date,Closed Date,Agency,Agency Name,Complaint Type,Descriptor,Location Type,Incident Zip,Incident Address,...,Vehicle Type,Taxi Company Borough,Taxi Pick Up Location,Bridge Highway Name,Bridge Highway Direction,Road Ramp,Bridge Highway Segment,Latitude,Longitude,Location
52067,32379764,01/09/2016 04:17:37 PM,01/13/2016 06:15:47 PM,HPD,Department of Housing Preservation and Develop...,HEAT/HOT WATER,APARTMENT ONLY,RESIDENTIAL BUILDING,10030.0,118 WEST 137 STREET,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.815738,-73.940730,"(40.81573796742099, -73.94072964712291)"
253002,33400414,05/21/2016 12:43:01 AM,05/21/2016 03:28:52 AM,NYPD,New York City Police Department,Noise - Residential,Loud Music/Party,Residential Building/House,11231.0,89 VERONA STREET,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.679630,-74.009287,"(40.6796297972724, -74.00928738265931)"
128,32309437,01/01/2016 12:38:28 AM,01/01/2016 12:50:57 AM,NYPD,New York City Police Department,Noise - Commercial,Loud Music/Party,Club/Bar/Restaurant,10009.0,16 1 AVENUE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.723494,-73.988253,"(40.72349367369547, -73.98825325266078)"
358333,32813209,03/02/2016 10:52:00 AM,03/02/2016 10:52:00 AM,DOT,Department of Transportation,Street Light Condition,Street Light Out,NaN,11422.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.658688,-73.729434,"(40.65868770480924, -73.72943448563208)"
107244,33191181,04/22/2016 12:31:00 PM,04/22/2016 07:10:00 PM,DEP,Department of Environmental Protection,Water System,Leak (Use Comments) (WA2),NaN,11229.0,2042 EAST 21 STREET,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.602889,-73.951027,"(40.60288926307405, -73.95102719178794)"
102415,32442963,01/18/2016 11:08:25 PM,01/19/2016 01:27:50 AM,NYPD,New York City Police Department,Illegal Parking,Blocked Hydrant,Street/Sidewalk,10304.0,30 MAXIE COURT,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.621700,-74.085917,"(40.62169962366208, -74.08591659326042)"
225575,34769996,11/13/2016 03:50:50 AM,11/13/2016 05:16:52 AM,NYPD,New York City Police Department,Noise - Residential,Loud Music/Party,Residential Building/House,11207.0,340 WILLIAMS AVENUE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.667670,-73.898657,"(40.66767046479791, -73.89865733007855)"
274089,34163180,08/24/2016 02:37:17 PM,08/26/2016 02:17:34 AM,HPD,Department of Housing Preservation and Develop...,HEAT/HOT WATER,ENTIRE BUILDING,RESIDENTIAL BUILDING,11368.0,98-25 HORACE HARDING EXPRESSWAY,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.735678,-73.859843,"(40.73567803993014, -73.85984312437)"
149592,32529895,01/26/2016 06:15:00 AM,01/27/2016 12:00:00 PM,DSNY,BCC - Brooklyn North,Other Enforcement,E10 Street Obstruction,Sidewalk,11226.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.639692,-73.953205,"(40.6396923391357, -73.95320533582682)"
209212,33336131,05/12/2016 11:48:00 AM,05/12/2016 11:48:00 AM,DOT,Department of Transportation,Street Light Condition,Lamppost Base Door/Cover Open,NaN,11206.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.699999,-73.957224,"(40.69999939459152, -73.95722387138059)"
180665,34013472,08/05/2016 06:49:41 PM,08/06/2016 07:42:27 AM,NYPD,New York City Police Department,Animal Abuse,Neglected,Residential Building/House,10465.0,3136 SPENCER DRIVE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.843798,-73.823458,"(40.843798076603946, -73.82345833260943)"
268890,32686689,02/15/2016 01:50:37 PM,02/16/2016 09:05:29 AM,HPD,Department of Housing Preservation and Develop...,HEAT/HOT WATER,APARTMENT ONLY,RESIDENTIAL BUILDING,10453.0,1991 GRAND AVENUE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.852627,-73.910637,"(40.85262672595807, -73.91063669045153)"
114387,33195988,04/23/2016 11:38:12 PM,04/24/2016 12:36:02 AM,NYPD,New York City Police Department,Noise - Commercial,Banging/Pounding,Club/Bar/Restaurant,11419.0,115-22 LIBERTY AVENUE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.685764,-73.827464,"(40.68576439562681, -73.82746439483222)"
262696,34146254,08/22/2016 11:36:33 AM,08/25/2016 04:02:37 PM,DOT,Department of Transportation,Street Condition,Cave-in,Street,11367.0,72-39 141 STREET,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.725039,-73.823473,"(40.72503874513637, -73.82347349099965)"
58017,32384209,01/11/2016 12:14:48 AM,01/11/2016 12:52:18 AM,NYPD,New York City Police Department,Noise - Vehicle,Car/Truck Music,Street/Sidewalk,10035.0,1990 LEXINGTON AVENUE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.802074,-73.939113,"(40.80207389040762, -73.93911280947297)"
178824,34696868,11/03/2016 06:22:51 PM,01/27/2017 01:45:23 PM,HPD,Department of Housing Preservation and Develop...,PAINT/PLASTER,WALL,RESIDENTIAL BUILDING,10453.0,123 WEST 183 STREET,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.860119,-73.910117,"(40.860119359988815, -73.91011688841901)"
289010,32717798,02/18/2016 12:10:05 PM,02/23/2016 11:23:17 AM,HPD,Department of Housing Preservation and Develop...,HEAT/HOT WATER,ENTIRE BUILDING,RESIDENTIAL BUILDING,11369.0,32-47 107 STREET,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.758877,-73.862090,"(40.75887665292679, -73.86209004382094)"
252147,34125742,08/19/2016 10:00:14 PM,08/29/2016 12:39:43 PM,HPD,Department of Housing Preservation and Develop...,FLOORING/STAIRS,FLOOR,RESIDENTIAL BUILDING,10463.0,213 WEST 238 STREET,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.884692,-73.899249,"(40.88469186998406, -73.89924871272149)"
249914,32668298,02/13/2016 10:44:53 AM,02/13/2016 03:31:35 PM,NYPD,New York City Police Department,Blocked Driveway,Partial Access,Street/Sidewalk,11218.0,429 CONEY ISLAND AVENUE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.647227,-73.971081,"(40.647227169437464, -73.9710811136193)"
155365,33977821,07/31/2016 11:31:27 PM,08/01/2016 02:52:21 AM,NYPD,New York City Police Department,Blocked Driveway,Partial Access,Street/Sidewalk,11204.0,1631 55 STREET,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.627144,-73.988108,"(40.62714384062214, -73.9881080975864)"
407770,32892416,03/11/2016 05:28:48 PM,03/19/2016 01:47:40 PM,HPD,Department of Housing Preservation and Develop...,PAINT/PLASTER,WALL,RESIDENTIAL BUILDING,10453.0,2264 GRAND AVENUE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.858790,-73.905831,"(40.85879025103595, -73.9058312181596)"
435523,35058749,12/19/2016 07:02:16 PM,12/21/2016 09:24:56 AM,DOT,Department of Transportation,Broken Muni Meter,Credit Card Stuck in Meter,Street,10065.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.764988,-73.961149,"(40.76498834054505, -73.96114949015954)"
260452,32682265,02/14/2016 01:36:00 PM,02/17/2016 11:40:00 PM,DOT,Department of Transportation,Street Light Condition,Street Light Out,NaN,NaN,323 79 ST E,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
311905,34225422,09/01/2016 11:59:26 AM,09/16/2016 11:47:28 AM,DOT,Department of Transportation,Broken Muni Meter,Coin or Card Did Not Register,Street,11210.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.633997,-73.947773,"(40.63399731095844, -73.94777257477888)"
507520,33030837,03/31/2016 10:34:13 AM,04/01/2016 10:00:00 AM,DOT,Department of Transportation,Street Condition,Pothole,NaN,11377.0,24-55 BROOKLYN QNS EXPRESSWAY,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.764199,-73.902694,"(40.76419899486703, -73.90269436325113)"
215010,32620486,02/07/2016 01:11:07 PM,02/09/2016 10:12:22 AM,HPD,Department of Housing Preservation and Develop...,HEAT/HOT WATER,ENTIRE BUILDING,RESIDENTIAL BUILDING,10467.0,2751 BARKER AVENUE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.866011,-73.869153,"(40.86601147424283, -73.86915301642351)"
273841,32703741,02/16/2016 09:03:00 AM,02/17/2016 09:03:00 AM,DEP,Department of Environmental Protection,Lead,Lead Kit Request (Residential) (L10),NaN,11364.0,79-49 210 STREET,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.734215,-73.761202,"(40.73421472278177, -73.76120215588793)"
53423,34522035,10/12/2016 11:33:16 AM,10/12/2016 03:02:12 PM,NYPD,New York City Police Department,Noise - Residential,Loud Music/Party,Residential Building/House,10010.0,340 EAST 22 STREET,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.736777,-73.980352,"(40.73677721262611, -73.98035202981409)"
80871,34555538,10/17/2016 04:58:18 PM,04/13/2017 02:56:32 PM,DOT,Department of Transportation,Street Sign - Damaged,Other/Unknown,Street,11355.0,44-10 COLLEGE POINT BOULEVARD,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.753406,-73.832736,"(40.753405911087334, -73.83273570743079)"
294506,33459382,05/29/2016 01:41:24 AM,05/29/2016 02:54:09 AM,NYPD,New York City Police Department,Noise - Residential,Loud Music/Party,Residential Building/House,10472.0,1010 SOUND VIEW AVENUE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.825259,-73.870183,"(40.825259196561575, -73.87018343562083)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
250744,33406527,05/20/2016 05:17:00 PM,05/23/2016 12:00:00 PM,DSNY,A - Queens,Dirty Conditions,E3A Dirty Area/Alleyway,Lot,11356.0,122-17 9 AVENUE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.789437,-73.845328,"(40.789437284402496, -73.84532808053899)"
442996,34416756,09/27/2016 10:20:59 PM,09/28/2016 01:56:54 AM,NYPD,New York City Police Department,Noise - Residential,Loud Music/Party,Residential Building/House,10003.0,56 EAST 7 STREET,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.727679,-73.987434,"(40.72767934168179, -73.98743351019144)"
74843,33851151,07/15/2016 08:37:31 PM,07/15/2016 11:58:03 PM,NYPD,New York City Police Department,Noise - Street/Sidewalk,Loud Music/Party,Street/Sidewalk,10455.0,783 SOUTHERN BOULEVARD,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.815792,-73.896770,"(40.81579207585081, -73.89676991936834)"
207432,32607263,02/05/2016 06:18:00 PM,02/05/2016 07:10:00 PM,DOT,Department of Transportation,Traffic Signal Condition,Controller,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
160992,34669108,10/31/2016 03:27:00 PM,11/01/2016 09:56:00 AM,DEP,Department of Environmental Protection,Water Quality,"No Sampling Required, Requested Information (QG2)",NaN,10003.0,318 EAST 15 STREET,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.732592,-73.983417,"(40.73259194537532, -73.98341663930714)"
100690,33898172,07/21/2016 12:20:00 AM,07/21/2016 12:40:00 AM,DOT,Department of Transportation,Traffic Signal Condition,LED Lense,NaN,11355.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.752241,-73.820850,"(40.75224073198343, -73.82084964070637)"
485103,35126783,12/29/2016 07:05:08 PM,12/30/2016 09:27:44 AM,NYPD,New York City Police Department,Illegal Parking,Posted Parking Sign Violation,Street/Sidewalk,NaN,3034-3098 54TH ST,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
312236,34889522,11/29/2016 01:56:14 PM,12/12/2016 10:34:47 AM,HPD,Department of Housing Preservation and Develop...,APPLIANCE,REFRIGERATOR,RESIDENTIAL BUILDING,11211.0,144 BROADWAY,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.710251,-73.963573,"(40.71025053064958, -73.96357283920541)"
255939,32684721,02/14/2016 02:45:38 AM,02/14/2016 04:10:42 AM,NYPD,New York City Police Department,Noise - Residential,Loud Music/Party,Residential Building/House,10029.0,1309 5 AVENUE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.797308,-73.948901,"(40.797308308526034, -73.94890132984646)"
148600,33972728,07/30/2016 10:45:00 AM,08/01/2016 12:00:00 PM,DSNY,BCC - Queens East,Missed Collection (All Materials),1RG Missed Recycling Paper,Sidewalk,11429.0,102-38 221 STREET,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.712403,-73.733069,"(40.7124033843078, -73.73306886967084)"
452929,34431345,09/30/2016 12:10:14 AM,09/30/2016 01:35:23 AM,NYPD,New York City Police Department,Noise - Residential,Banging/Pounding,Residential Building/House,10025.0,909 AMSTERDAM AVENUE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.799442,-73.966424,"(40.79944190874345, -73.96642433930961)"
221686,34762281,11/12/2016 11:32:16 AM,11/15/2016 02:17:31 AM,HPD,Department of Housing Preservation and Develop...,HEAT/HOT WATER,ENTIRE BUILDING,RESIDENTIAL BUILDING,10031.0,18 ST NICHOLAS PLACE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.827640,-73.942121,"(40.827639771078346, -73.94212103335633)"
414816,32898542,03/13/2016 08:54:00 AM,03/14/2016 12:00:00 PM,DSNY,BCC - Queens West,Missed Collection (All Materials),1 Missed Collection,Sidewalk,11418.0,100-04 92 AVENUE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.690825,-73.844551,"(40.690825407418345, -73.844550771038)"
308073,34216328,08/31/2016 03:06:23 PM,09/10/2016 12:02:35 PM,HPD,Department of Housing Preservation and Develop...,UNSANITARY CONDITION,MOLD,RESIDENTIAL BUILDING,10453.0,1694 WALTON AVENUE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.845724,-73.911531,"(40.84572448023011, -73.91153147970789)"
363119,34957864,12/08/2016 10:16:00 AM,12/09/2016 12:00:00 PM,DSNY,Brooklyn North 03,Sanitation Condition,15 Street Cond/Dump-Out/Drop-Off,Street,11216.0,215 MONROE STREET,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.685575,-73.949730,"(40.68557534753877, -73.94972972008468)"
382319,33599836,06/15/2016 09:05:58 AM,06/15/2016 04:05:39 PM,NYPD,New York City Police Department,Illegal Parking,Blocked Sidewalk,Street/Sidewalk,11234.0,2235 FLATBUSH AVENUE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.615306,-73.928787,"(40.615306069870236, -73.92878729679715)"
107053,33189105,04/22/2016 11:54:35 AM,04/22/2016 01:30:12 PM,NYPD,New York City Police Department,Illegal Parking,Blocked Hydrant,Street/Sidewalk,11692.0,149 OCEAN LANE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.589802,-73.794930,"(40.58980242870453, -73.79492969781204)"
297308,32723538,02/19/2016 06:23:00 PM,02/19/2016 06:25:00 PM,DEP,Department of Environmental Protection,Water System,Leak (Use Comments) (WA2),NaN,11226.0,137 EAST 28 STREET,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.646081,-73.950970,"(40.64608126854771, -73.95097026492991)"
109162,32453194,01/19/2016 05:12:04 PM,01/20/2016 07:39:08 PM,HPD,Department of Housing Preservation and Develop...,HEAT/HOT WATER,APARTMENT ONLY,RESIDENTIAL BUILDING,11209.0,7032 4 AVENUE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.633499,-74.023988,"(40.63349888438347, -74.02398783000476)"
8579,34452195,10/03/2016 12:38:30 AM,10/03/2016 08:49:52 PM,NYPD,New York City Police Department,Noise - Residential,Banging/Pounding,Residential Building/House,11101.0,40-13 VERNON BOULEVARD,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.757648,-73.945972,"(40.75764826759628, -73.94597190403468)"
257161,34811356,11/19/2016 12:11:11 AM,11/19/2016 02:21:41 AM,NYPD,New York City Police Department,Noise - Residential,Loud Music/Party,Residential Building/House,10459.0,1358 PROSPECT AVENUE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.830227,-73.897221,"(40.830226953775934, -73.89722089407267)"
507957,33030633,03/31/2016 11:29:00 AM,03/31/2016 12:15:00 PM,DOT,Department of Transportation,Traffic Signal Condition,Pedestrian Signal,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
238965,33381405,05/18/2016 12:39:10 PM,05/18/2016 01:31:54 PM,NYPD,New York City Police Department,Derelict Vehicle,With License Plate,Street/Sidewalk,10301.0,98 MONTGOMERY AVENUE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.639579,-74.078268,"(40.63957915651766, -74.07826842673202)"
409670,35020077,12/15/2016 07:59:24 PM,12/21/2016 06:33:39 PM,HPD,Department of Housing Preservation and Develop...,HEAT/HOT WATER,ENTIRE BUILDING,RESIDENTIAL BUILDING,10467.0,115 EAST MOSHOLU PARKWAY NORTH,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.877386,-73.882051,"(40.877385676249666, -73.88205087634928)"
84492,33865108,07/17/2016 10:23:00 PM,07/19/2016 01:50:00 PM,DOT,Department of Transportation,Street Light Condition,Street Light Out,NaN,11379.0,JUNIPER VALLEY PARK,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.722145,-73.878051,"(40.72214514304138, -73.87805055504032)"
290703,34855851,11/24/2016 08:43:25 PM,12/02/2016 02:10:32 AM,HPD,Department of Housing Preservation and Develop...,HEAT/HOT WATER,ENTIRE BUILDING,RESIDENTIAL BUILDING,10473.0,1965 LAFAYETTE AVENUE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.822205,-73.856893,"(40.82220506426356, -73.85689326155203)"
344684,32794009,02/28/2016 04:53:39 PM,02/29/2016 07:39:29 AM,NYPD,New York City Police Department,Noise - Residential,Loud Music/Party,Residential Building/House,11208.0,175 RICHMOND STREET,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.683239,-73.876816,"(40.68323948715239, -73.87681649517796)"
60282,33125501,04/13/2016 12:07:38 AM,04/16/2016 01:13:43 AM,HPD,Department of Housing Preservation and Develop...,PAINT/PLASTER,WALL,RESIDENTIAL BUILDING,10466.0,3626 PRATT AVENUE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.885162,-73.835634,"(40.88516225792812, -73.83563375095031)"
411585,34371632,09/21/2016 02:21:51 PM,09/21/2016 06:14:42 PM,NYPD,New York City Police Department,Noise - Residential,Loud Music/Party,Residential Building/House,11205.0,56 MONUMENT WALK,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.694865,-73.979214,"(40.69486451742089, -73.9792140115764)"
49260,33099901,04/10/2016 09:15:11 PM,04/15/2016 02:33:37 PM,HPD,Department of Housing Preservation and Develop...,GENERAL,CABINET,RESIDENTIAL BUILDING,11212.0,480 EAST 94 STREET,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.655601,-73.918091,"(40.65560067459487, -73.918090702944)"

In [11]:
pop_df = pd.read_csv('ACS_16_Pop.csv', header=[1])
income_df = pd.read_csv('ACS_16_Income.csv', header=[1])
rent_df = pd.read_csv('ACS_16_Rent.csv', header=[1])

In [5]:
pop_df.head()

               Id    Id2    Geography  Estimate; Total  Margin of Error; Total
0  8600000US06390   6390  ZCTA5 06390              303                     151
1  8600000US07421   7421  ZCTA5 07421             7281                     512
2  8600000US10001  10001  ZCTA5 10001            23332                    1740
3  8600000US10002  10002  ZCTA5 10002            78096                    2456
4  8600000US10003  10003  ZCTA5 10003            56767                    1934

In [12]:
pop_df = pop_df.drop(columns=['Id', 'Geography', 'Margin of Error; Total'])
pop_df = pop_df.drop(pop_df.index[0])
pop_df = pop_df.drop(pop_df.index[0])
pop_df = pop_df.rename(index=str, columns={'Id2': 'Zip Code', 'Estimate; Total': 'Population Estimate'})

In [13]:
pop_df.head()

   Zip Code  Population Estimate
2     10001                23332
3     10002                78096
4     10003                56767
5     10004                 3044
6     10005                 8710

In [14]:
income_df.head()

,Id,Id2,Geography,Total; Estimate; Households,Total; Margin of Error; Households,Median income (dollars); Estimate; Households,Median income (dollars); Margin of Error; Households,Total; Estimate; Households - One race-- - White,Total; Margin of Error; Households - One race-- - White,Median income (dollars); Estimate; Households - One race-- - White,...,Median income (dollars); Estimate; PERCENT ALLOCATED - Household income in the past 12 months,Median income (dollars); Margin of Error; PERCENT ALLOCATED - Household income in the past 12 months,Total; Estimate; PERCENT ALLOCATED - Family income in the past 12 months,Total; Margin of Error; PERCENT ALLOCATED - Family income in the past 12 months,Median income (dollars); Estimate; PERCENT ALLOCATED - Family income in the past 12 months,Median income (dollars); Margin of Error; PERCENT ALLOCATED - Family income in the past 12 months,Total; Estimate; PERCENT ALLOCATED - Nonfamily income in the past 12 months,Total; Margin of Error; PERCENT ALLOCATED - Nonfamily income in the past 12 months,Median income (dollars); Estimate; PERCENT ALLOCATED - Nonfamily income in the past 12 months,Median income (dollars); Margin of Error; PERCENT ALLOCATED - Nonfamily income in the past 12 months
0,8600000US06390,6390,ZCTA5 06390,118,54,152652,17233,100,22.2,152652,...,(X),(X),63,(X),(X),(X),4.4,(X),(X),(X)
1,8600000US07421,7421,ZCTA5 07421,2575,180,94375,11261,95.5,2.5,96591,...,(X),(X),43.4,(X),(X),(X),31.7,(X),(X),(X)
2,8600000US10001,10001,ZCTA5 10001,11967,548,85168,11872,69.3,3.4,101797,...,(X),(X),31.5,(X),(X),(X),18.4,(X),(X),(X)
3,8600000US10002,10002,ZCTA5 10002,33327,636,35594,2970,37.5,1.8,67933,...,(X),(X),36.1,(X),(X),(X),25.3,(X),(X),(X)
4,8600000US10003,10003,ZCTA5 10003,27258,681,100791,4905,81.9,1.9,102454,...,(X),(X),30.3,(X),(X),(X),21.9,(X),(X),(X)

In [15]:
income_df = income_df.drop(income_df.columns[0], axis=1)
income_df = income_df.drop(income_df.columns[1], axis=1)
income_df = income_df.drop(income_df.columns[1], axis=1)
income_df = income_df.drop(income_df.columns[1], axis=1)
income_df = income_df.drop(income_df.columns[2:120], axis=1)
income_df = income_df.drop(income_df.index[0])
income_df = income_df.drop(income_df.index[0])
income_df = income_df.rename(index=str, columns={'Id2': 'Zip Code', 'Median income (dollars); Estimate; Households': 'Median Estimate'})

In [16]:
income_df.head()

   Zip Code Median Estimate
2     10001           85168
3     10002           35594
4     10003          100791
5     10004          123056
6     10005          130116

In [17]:
rent_df.head()

,Id,Id2,Geography,Estimate; Median gross rent,Margin of Error; Median gross rent
0,8600000US06390,6390,ZCTA5 06390,1388,33
1,8600000US07421,7421,ZCTA5 07421,1772,191
2,8600000US10001,10001,ZCTA5 10001,2114,188
3,8600000US10002,10002,ZCTA5 10002,919,35
4,8600000US10003,10003,ZCTA5 10003,2117,82

In [18]:
rent_df = rent_df.drop(columns=['Id', 'Geography', 'Margin of Error; Median gross rent'])
rent_df = rent_df.drop(rent_df.index[0])
rent_df = rent_df.drop(rent_df.index[0])
rent_df = rent_df.rename(index=str, columns={'Id2': 'Zip Code', 'Estimate; Median gross rent': 'Gross Rent Estimate'})

In [19]:
rent_df.head()

   Zip Code Gross Rent Estimate
2     10001                2114
3     10002                 919
4     10003                2117
5     10004                2911
6     10005                3005

In [20]:
rentandincome = pd.merge(rent_df, income_df, on='Zip Code')
rentandincome

      Zip Code Gross Rent Estimate Median Estimate
0        10001                2114           85168
1        10002                 919           35594
2        10003                2117          100791
3        10004                2911          123056
4        10005                3005          130116
5        10006                2847          125364
6        10007                3339          234958
7        10009                1554           60788
8        10010                2442          110142
9        10011                2029          114134
10       10012                2128          101815
11       10013                1663          104167
12       10014                2337          119026
13       10016                2440          102703
14       10017                2214          106795
15       10018                2849          105479
16       10019                2211           94477
17       10020                   -               -
18       10021                1961          115681
19       10022                2386          123693
20       10023                2256          115080
21       10024                1947          118594
22       10025                1450           80025
23       10026                1045           52082
24       10027                1063           42754
25       10028                2187          111302
26       10029                 911           32500
27       10030                 917           33720
28       10031                1174           41848
29       10032                1131           40054
...        ...                 ...             ...
1763     14865                 604           39132
1764     14867                 854           58411
1765     14869                 565           51597
1766     14870                 880           63376
1767     14871                 783           66575
1768     14872                 638           51293
1769     14873                 553           48770
1770     14874                 856           39231
1771     14877                 622           41250
1772     14878                 730           57404
1773     14879                 680           47083
1774     14880                 664           50726
1775     14881                   -          109803
1776     14882                1253           67236
1777     14883                 713           46354
1778     14884                   -           47917
1779     14885                   -           53636
1780     14886                 852           66661
1781     14889                 819           55375
1782     14891                 677           44161
1783     14892                 686           46125
1784     14893                   -               -
1785     14894                 710           43828
1786     14895                 598           41849
1787     14897                 490           45000
1788     14898                 706           40769
1789     14901                 659           26944
1790     14903                 674           53413
1791     14904                 714           37927
1792     14905                 769           57297

[1793 rows x 3 columns]

In [20]:
data = pd.merge(rentandincome, pop_df, on='Zip Code')
data

      Zip Code Gross Rent Estimate Median Estimate  Population Estimate
0        10001                2114           85168                23332
1        10002                 919           35594                78096
2        10003                2117          100791                56767
3        10004                2911          123056                 3044
4        10005                3005          130116                 8710
5        10006                2847          125364                 3277
6        10007                3339          234958                 6740
7        10009                1554           60788                59799
8        10010                2442          110142                32854
9        10011                2029          114134                50404
10       10012                2128          101815                24536
11       10013                1663          104167                28211
12       10014                2337          119026                31464
13       10016                2440          102703                50444
14       10017                2214          106795                16533
15       10018                2849          105479                 9684
16       10019                2211           94477                39505
17       10020                   -               -                    0
18       10021                1961          115681                45261
19       10022                2386          123693                30262
20       10023                2256          115080                60307
21       10024                1947          118594                58516
22       10025                1450           80025                94717
23       10026                1045           52082                38540
24       10027                1063           42754                64120
25       10028                2187          111302                48205
26       10029                 911           32500                79411
27       10030                 917           33720                30358
28       10031                1174           41848                60778
29       10032                1131           40054                63189
...        ...                 ...             ...                  ...
1763     14865                 604           39132                 3005
1764     14867                 854           58411                 5800
1765     14869                 565           51597                 1359
1766     14870                 880           63376                 9938
1767     14871                 783           66575                 5294
1768     14872                 638           51293                  769
1769     14873                 553           48770                 2662
1770     14874                 856           39231                  255
1771     14877                 622           41250                  372
1772     14878                 730           57404                  603
1773     14879                 680           47083                 1999
1774     14880                 664           50726                 1407
1775     14881                   -          109803                  287
1776     14882                1253           67236                 3985
1777     14883                 713           46354                 3920
1778     14884                   -           47917                  223
1779     14885                   -           53636                  748
1780     14886                 852           66661                 7269
1781     14889                 819           55375                 1779
1782     14891                 677           44161                 4310
1783     14892                 686           46125                 8299
1784     14893                   -               -                    6
1785     14894                 710           43828                 1325
1786     14895                 598           41849                 9446
1787     14897                 490           45000                  846
1788     14898                 706           40769                 1826
1789     14901                 659           26944                16334
1790     14903                 674           53413                 7143
1791     14904                 714           37927                15782
1792     14905                 769           57297                 9150

[1793 rows x 4 columns]