In [106]:
import pandas as pd
rent_df = pd.read_csv('ACS_11_16_Median_Gross_Rent.csv', header=[1])
rent_df = rent_df.drop(columns=['Id', 'Geography', 'Margin of Error; Median gross rent'])
rent_df = rent_df.drop(columns=['Margin of Error; Median gross rent.{}'.format(i) for i in range(1,6)])
rent_df.head()
type(rent_df)

pandas.core.frame.DataFrame

In [110]:
rent_df.rename(index=str, columns={'Estimate; Median gross rent': '2016 Median Gross Rent', 'Estimate; Median gross rent.1': '2015 Median Gross Rent', 'Estimate; Median gross rent.2':'2014 Median Gross Rent', 'Estimate; Median gross rent.3':'2013 Median Gross Rent', 'Estimate; Median gross rent.4':'2012 Median Gross Rent', 'Estimate; Median gross rent.5':'2011 Median Gross Rent'})

,Id2,2016 Median Gross Rent,2015 Median Gross Rent,2014 Median Gross Rent,2013 Median Gross Rent,2012 Median Gross Rent,2011 Median Gross Rent
0,10001,2114,1989,1865,1830,1771,1580
1,10002,919,882,863,848,803,770
2,10003,2117,2030,1955,1855,1836,1747
3,10004,2911,2851,"2,000+","2,000+","2,000+","2,000+"
4,10005,3005,2918,"2,000+","2,000+","2,000+","2,000+"
5,10006,2847,2824,"2,000+","2,000+","2,000+","2,000+"
6,10007,3339,3423,"2,000+","2,000+","2,000+","2,000+"
7,10009,1554,1485,1470,1436,1400,1322
8,10010,2442,2295,"2,000+","2,000+","2,000+",1946
9,10011,2029,2000,1933,1911,1793,1754
10,10012,2128,2027,1919,1843,1751,1710
11,10013,1663,1512,1462,1388,1236,1165
12,10014,2337,2281,"2,000+","2,000+","2,000+","2,000+"
13,10016,2440,2327,"2,000+","2,000+","2,000+","2,000+"
14,10017,2214,2218,"2,000+","2,000+","2,000+",1988
15,10018,2849,2784,"2,000+","2,000+","2,000+","2,000+"
16,10019,2211,2169,"2,000+",1984,1875,1803
17,10020,-,-,-,-,-,-
18,10021,1961,1913,1876,1859,1846,1843
19,10022,2386,2259,"2,000+","2,000+","2,000+","2,000+"
20,10023,2256,2173,"2,000+",1951,1902,1878
21,10024,1947,1849,1828,1905,1870,1777
22,10025,1450,1428,1438,1451,1390,1277
23,10026,1045,992,944,914,884,875
24,10027,1063,1026,978,950,905,849
25,10028,2187,2081,"2,000+",1944,1930,1881
26,10029,911,886,885,853,794,729
27,10030,917,905,884,823,779,742
28,10031,1174,1150,1098,1062,1024,998
29,10032,1131,1109,1091,1035,992,977
...,...,...,...,...,...,...,...
1763,14865,604,584,577,552,529,535
1764,14867,854,519,872,840,852,797
1765,14869,565,707,535,596,583,611
1766,14870,880,665,805,795,755,713
1767,14871,783,712,794,829,794,829
1768,14872,638,689,649,759,755,754
1769,14873,553,775,656,623,617,648
1770,14874,856,NaN,833,820,810,764
1771,14877,622,NaN,609,554,550,542
1772,14878,730,NaN,743,741,942,1078
1773,14879,680,NaN,733,718,696,695
1774,14880,664,NaN,667,619,550,598
1775,14881,-,NaN,905,326,459,458
1776,14882,1253,NaN,864,732,706,702
1777,14883,713,NaN,912,805,811,735
1778,14884,-,NaN,782,781,778,779
1779,14885,-,NaN,623,630,620,608
1780,14886,852,NaN,848,808,831,842
1781,14889,819,NaN,800,827,859,816
1782,14891,677,NaN,594,583,570,546
1783,14892,686,NaN,671,625,590,565
1784,14893,-,NaN,-,-,-,-
1785,14894,710,NaN,610,544,549,614
1786,14895,598,NaN,597,586,593,588
1787,14897,490,NaN,531,518,505,550
1788,14898,706,NaN,593,575,499,491
1789,14901,659,NaN,628,600,589,574
1790,14903,674,NaN,718,717,674,679
1791,14904,714,NaN,697,681,684,680
1792,14905,769,NaN,814,767,735,692