In [1]:
import pandas as pd
q1_df = pd.read_csv('311q1.csv')
q2_df = pd.read_csv('311q2.csv')
q3_df = pd.read_csv('311q3.csv')
q4_df = pd.read_csv('311q4.csv')

/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:2785: DtypeWarning: Columns (17) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [2]:
df = pd.concat([q1_df, q2_df, q3_df, q4_df])

In [80]:
df

,Unique Key,Created Date,Closed Date,Agency,Agency Name,Complaint Type,Descriptor,Location Type,Incident Zip,Incident Address,...,Vehicle Type,Taxi Company Borough,Taxi Pick Up Location,Bridge Highway Name,Bridge Highway Direction,Road Ramp,Bridge Highway Segment,Latitude,Longitude,Location
0,32313858,01/01/2016 12:00:00 AM,01/11/2016 12:00:00 AM,DOHMH,Department of Health and Mental Hygiene,Rodent,Condition Attracting Rodents,Commercial Building,11412,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.691994,-73.761101,"(40.69199443321462, -73.76110094542425)"
1,32313744,01/01/2016 12:00:00 AM,01/05/2016 12:00:01 AM,DOHMH,Department of Health and Mental Hygiene,Food Poisoning,1 or 2,Restaurant/Bar/Deli/Bakery,10003,51 UNIVERSITY PLACE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.732483,-73.994014,"(40.73248319369935, -73.99401397947217)"
2,32313734,01/01/2016 12:00:00 AM,01/11/2016 11:53:05 AM,DOHMH,Department of Health and Mental Hygiene,Rodent,Rat Sighting,1-2 Family Dwelling,11412,191-47 114 DRIVE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.696738,-73.761441,"(40.69673811577188, -73.76144097018195)"
3,32313707,01/01/2016 12:00:00 AM,NaN,DOHMH,Department of Health and Mental Hygiene,Rodent,Rat Sighting,3+ Family Apt. Building,10454,283 CYPRESS AVENUE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.806710,-73.913881,"(40.8067101128063, -73.91388071792183)"
4,32313626,01/01/2016 12:00:00 AM,12/11/2015 12:00:00 AM,DOHMH,Department of Health and Mental Hygiene,Rodent,Rat Sighting,1-2 Family Dwelling,11412,191-45 114 DRIVE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.696738,-73.761441,"(40.69673811577188, -73.76144097018195)"
5,32313618,01/01/2016 12:00:00 AM,11/23/2015 12:00:00 AM,DOHMH,Department of Health and Mental Hygiene,Unsanitary Animal Pvt Property,Cat,3+ Family Apartment Building,10462,2198 CRUGER AVENUE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.856317,-73.866627,"(40.85631703985628, -73.86662717636435)"
6,32313614,01/01/2016 12:00:00 AM,01/20/2016 12:00:00 AM,DOHMH,Department of Health and Mental Hygiene,Rodent,Mouse Sighting,3+ Family Apt. Building,11210,2300 KINGS HIGHWAY,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.611521,-73.950394,"(40.61152137455337, -73.95039416824221)"
7,32313579,01/01/2016 12:00:00 AM,01/20/2016 12:00:00 AM,DOHMH,Department of Health and Mental Hygiene,Rodent,Signs of Rodents,Other (Explain Below),11230,1555 E 19TH ST,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.612174,-73.954752,"(40.612173688837736, -73.95475174991557)"
8,32313511,01/01/2016 12:00:00 AM,01/05/2016 12:00:00 AM,DOHMH,Department of Health and Mental Hygiene,Rodent,Condition Attracting Rodents,3+ Family Apt. Building,10029,173 EAST 111 STREET,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.795148,-73.943244,"(40.795148304447196, -73.94324359929192)"
9,32313373,01/01/2016 12:00:00 AM,01/06/2016 12:00:00 AM,DOHMH,Department of Health and Mental Hygiene,Rodent,Rat Sighting,Other (Explain Below),NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,32313351,01/01/2016 12:00:00 AM,01/12/2016 12:00:00 AM,DOHMH,Department of Health and Mental Hygiene,Rodent,Rat Sighting,1-2 Family Dwelling,11213,1526 PRESIDENT STREET,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.667369,-73.937945,"(40.66736899256702, -73.93794529650128)"
11,32313307,01/01/2016 12:00:00 AM,01/04/2016 09:50:13 AM,DOHMH,Department of Health and Mental Hygiene,Food Poisoning,1 or 2,Restaurant/Bar/Deli/Bakery,11213,1133 EASTERN PARKWAY,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.668773,-73.930515,"(40.66877281544983, -73.93051457067465)"
12,32313302,01/01/2016 12:00:00 AM,01/07/2016 12:00:00 AM,DOHMH,Department of Health and Mental Hygiene,Rodent,Rat Sighting,Public Garden,11217,143 SOUTH PORTLAND AVENUE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.684925,-73.974148,"(40.68492467883407, -73.9741475846067)"
13,32313240,01/01/2016 12:00:00 AM,12/29/2015 12:00:00 AM,DOHMH,Department of Health and Mental Hygiene,Rodent,Rat Sighting,3+ Family Mixed Use Building,11203,651 BROOKLYN AVENUE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.658073,-73.945152,"(40.658073341365935, -73.94515150328259)"
14,32313219,01/01/2016 12:00:00 AM,11/23/2015 12:00:00 AM,DOHMH,Department of Health and Mental Hygiene,Rodent,Mouse Sighting,3+ Family Apt. Building,10029,2172 2ND AVENUE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.794120,-73.939579,"(40.79411991259857, -73.93957875121706)"
15,32312965,01/01/2016 12:00:00 AM,12/28/2015 06:03:08 PM,DOHMH,Department of Health and Mental Hygiene,Rodent,Signs of Rodents,3+ Family Mixed Use Building,10452,1555 GRANDCONCOURSE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.842209,-73.912284,"(40.84220908371895, -73.91228428654)"
16,32312964,01/01/2016 12:00:00 AM,01/11/2016 12:00:00 AM,DOHMH,Department of Health and Mental Hygiene,Rodent,Signs of Rodents,3+ Family Apt. Building,10467,660 ARNOW AVENUE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.867710,-73.868539,"(40.8677097446367, -73.86853864658009)"
17,32312963,01/01/2016 12:00:00 AM,01/12/2016 03:43:25 PM,DOHMH,Department of Health and Mental Hygiene,Rodent,Signs of Rodents,1-2 Family Dwelling,11208,987 CRESCENT STREET,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.663159,-73.866934,"(40.66315866212477, -73.86693409345021)"
18,32312944,01/01/2016 12:00:00 AM,12/07/2015 12:00:00 AM,DOHMH,Department of Health and Mental Hygiene,Rodent,Rat Sighting,Catch Basin/Sewer,10026,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.806708,-73.952857,"(40.80670793752896, -73.95285673474811)"
19,32312838,01/01/2016 12:00:00 AM,12/23/2015 12:00:00 AM,DOHMH,Department of Health and Mental Hygiene,Rodent,Rat Sighting,3+ Family Apt. Building,10472,1962 CROSS BRONX EXPRESSWAY,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.832238,-73.858046,"(40.832238434927426, -73.85804610902596)"
20,32312819,01/01/2016 12:00:00 AM,01/20/2016 12:00:00 AM,DOHMH,Department of Health and Mental Hygiene,Rodent,Mouse Sighting,3+ Family Apt. Building,11210,2300 KINGS HIGHWAY,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.611521,-73.950394,"(40.61152137455337, -73.95039416824221)"
21,32312712,01/01/2016 12:00:00 AM,10/23/2015 12:00:00 AM,DOHMH,Department of Health and Mental Hygiene,Rodent,Condition Attracting Rodents,Vacant Lot,11221,867 GREENE AVENUE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.690700,-73.933056,"(40.690699577459846, -73.93305555091219)"
22,32312557,01/01/2016 12:00:00 AM,01/06/2016 12:33:41 PM,DOHMH,Department of Health and Mental Hygiene,Rodent,Rat Sighting,3+ Family Apt. Building,11213,930 PROSPECT PLACE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.674070,-73.945831,"(40.67407023114603, -73.94583051728789)"
23,32312526,01/01/2016 12:00:00 AM,02/24/2016 12:00:00 AM,DOHMH,Department of Health and Mental Hygiene,Rodent,Rat Sighting,3+ Family Apt. Building,10038,182 SOUTH STREET,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.708878,-73.998557,"(40.708878414145865, -73.99855722705524)"
24,32312485,01/01/2016 12:00:00 AM,01/12/2016 12:00:00 AM,DOHMH,Department of Health and Mental Hygiene,Rodent,Condition Attracting Rodents,1-2 Family Dwelling,11378,59-38 58 ROAD,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.720443,-73.906799,"(40.72044280451212, -73.90679871568335)"
25,32312482,01/01/2016 12:00:00 AM,01/05/2016 12:00:00 AM,DOHMH,Department of Health and Mental Hygiene,Rodent,Condition Attracting Rodents,1-2 Family Dwelling,11420,114-30 132 STREET,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.680987,-73.809406,"(40.68098743614094, -73.80940633108645)"
26,32312138,01/01/2016 12:00:00 AM,NaN,DOHMH,Department of Health and Mental Hygiene,Rodent,Rat Sighting,Other (Explain Below),10468,2327 GRAND CONCOURSE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.858187,-73.899517,"(40.85818657925701, -73.89951661209484)"
27,32312122,01/01/2016 12:00:00 AM,01/12/2016 12:00:00 AM,DOHMH,Department of Health and Mental Hygiene,Rodent,Rat Sighting,3+ Family Apt. Building,11210,1145 EAST 35TH STREET,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.626136,-73.941755,"(40.626136087996805, -73.94175541087431)"
28,32312038,01/01/2016 12:00:00 AM,11/23/2015 12:00:00 AM,DOHMH,Department of Health and Mental Hygiene,Rodent,Mouse Sighting,3+ Family Apt. Building,10029,2172 2ND AVENUE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.794120,-73.939579,"(40.79411991259857, -73.93957875121706)"
29,32312037,01/01/2016 12:00:00 AM,11/23/2015 12:00:00 AM,DOHMH,Department of Health and Mental Hygiene,Rodent,Mouse Sighting,3+ Family Apt. Building,10029,2172 2ND AVENUE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.794120,-73.939579,"(40.79411991259857, -73.93957875121706)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94337,35143310,12/31/2016 11:47:28 AM,12/31/2016 06:02:16 PM,NYPD,New York City Police Department,Blocked Driveway,No Access,Street/Sidewalk,10030,144 WEST 136 STREET,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.815321,-73.941684,"(40.81532125640187, -73.94168377159775)"
94338,35138799,12/31/2016 11:47:35 AM,01/03/2017 03:00:15 AM,DOT,Department of Transportation,Highway Condition,Litter,Highway,NaN,NaN,...,NaN,NaN,NaN,Long Island Expwy,West/Manhattan Bound,Ramp,Queens Blvd (NY 25)/Woodhaven Blvd (Exit 19),NaN,NaN,NaN
94339,35139092,12/31/2016 11:48:27 AM,04/25/2018 12:00:00 AM,DOB,Department of Buildings,Building/Use,No Certificate Of Occupancy/Illegal/Contrary T...,NaN,11692,65-11 BAYFIELD AVENUE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.599074,-73.795996,"(40.59907353751493, -73.79599593038112)"
94340,35156983,12/31/2016 11:49:00 AM,01/05/2017 12:00:00 PM,DSNY,BCC - Queens East,Sanitation Condition,12 Dead Animals,Sidewalk,11361,33-21 204 STREET,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.768672,-73.784736,"(40.76867211768984, -73.78473613255994)"
94341,35139887,12/31/2016 11:49:28 AM,01/05/2017 12:00:00 AM,DOB,Department of Buildings,Elevator,Elevator - Defective/Not Working,NaN,11230,1122 OCEAN AVENUE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.634781,-73.958112,"(40.63478106237809, -73.95811236451411)"
94342,35141402,12/31/2016 11:49:35 AM,01/20/2017 11:46:07 AM,TLC,Taxi and Limousine Commission,Taxi Complaint,Driver Complaint,Street,10014,259 BLEECKER STREET,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.731226,-74.002988,"(40.7312262128821, -74.002987541591)"
94343,35137085,12/31/2016 11:50:00 AM,12/31/2016 02:50:00 PM,DEP,Department of Environmental Protection,Sewer,Sewer Backup (Use Comments) (SA),NaN,11362,251-14 THEBES AVENUE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.766431,-73.733091,"(40.766431377931454, -73.73309059354546)"
94344,35137681,12/31/2016 11:51:00 AM,12/31/2016 12:00:00 PM,DSNY,BCC - Brooklyn North,Derelict Vehicles,14 Derelict Vehicles,Street,11212,187 DUMONT AVENUE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.663595,-73.912692,"(40.66359499597502, -73.91269218067781)"
94345,35138196,12/31/2016 11:52:00 AM,01/09/2017 12:02:00 PM,DSNY,Department of Sanitation,Electronics Waste,Recycling Electronics,Sidewalk,10307,618 MAIN STREET,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.499705,-74.243692,"(40.499705106345715, -74.24369185984821)"
94346,35142141,12/31/2016 11:52:09 AM,12/31/2016 02:12:36 PM,NYPD,New York City Police Department,Blocked Driveway,No Access,Street/Sidewalk,11219,1140 43 STREET,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.640574,-73.992264,"(40.640574442069365, -73.99226384326894)"
94347,35140682,12/31/2016 11:52:14 AM,01/03/2017 04:16:42 PM,HPD,Department of Housing Preservation and Develop...,HEAT/HOT WATER,APARTMENT ONLY,RESIDENTIAL BUILDING,10468,3065 GRAND CONCOURSE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.874261,-73.886703,"(40.87426138597488, -73.88670285877397)"
94348,35140195,12/31/2016 11:52:14 AM,01/05/2017 12:29:19 PM,HPD,Department of Housing Preservation and Develop...,HEAT/HOT WATER,APARTMENT ONLY,RESIDENTIAL BUILDING,10458,2995 BOTANICAL SQUARE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.867716,-73.881612,"(40.86771566456841, -73.88161246880681)"
94349,35141055,12/31/2016 11:53:06 AM,01/04/2017 02:11:58 AM,HPD,Department of Housing Preservation and Develop...,HEAT/HOT WATER,APARTMENT ONLY,RESIDENTIAL BUILDING,10467,3501 DECATUR AVENUE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.878973,-73.872462,"(40.878972888883, -73.8724616112776)"
94350,35141641,12/31/2016 11:53:14 AM,01/03/2017 12:00:00 AM,DOB,Department of Buildings,General Construction/Plumbing,Working Contrary To Stop Work Order,NaN,11375,108-25 UNION TURNPIKE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.708470,-73.845386,"(40.70846991890642, -73.84538610459826)"
94351,35141001,12/31/2016 11:53:22 AM,12/31/2016 05:56:35 PM,NYPD,New York City Police Department,Noise - Residential,Loud Music/Party,Residential Building/House,10467,3136 PERRY AVENUE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.873454,-73.878182,"(40.87345399929054, -73.8781816453512)"
94352,35142961,12/31/2016 11:53:36 AM,12/31/2016 03:02:18 PM,NYPD,New York City Police Department,Noise - Residential,Banging/Pounding,Residential Building/House,10474,675 COSTER STREET,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.813593,-73.887211,"(40.81359283231739, -73.88721075139193)"
94353,35142860,12/31/2016 11:54:19 AM,01/04/2017 09:23:43 AM,HPD,Department of Housing Preservation and Develop...,HEAT/HOT WATER,ENTIRE BUILDING,RESIDENTIAL BUILDING,11432,150-01 88 AVENUE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.705783,-73.805826,"(40.705783240181724, -73.80582604644991)"
94354,35138807,12/31/2016 11:54:57 AM,12/31/2016 01:37:40 PM,NYPD,New York City Police Department,Illegal Parking,Overnight Commercial Storage,Street/Sidewalk,11418,84-37 113 STREET,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.702207,-73.837794,"(40.70220688751647, -73.83779435863113)"
94355,35139917,12/31/2016 11:56:00 AM,01/03/2017 12:00:00 PM,DSNY,BCC - Queens East,Sanitation Condition,12 Dead Animals,Sidewalk,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
94356,35140273,12/31/2016 11:56:04 AM,NaN,DPR,Department of Parks and Recreation,New Tree Request,For One Address,NaN,10021,23 EAST 76TH STREET,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.774596,-73.963884,"(40.77459582011446, -73.96388424867904)"
94357,35143073,12/31/2016 11:56:22 AM,01/19/2017 11:18:23 AM,DOT,Department of Transportation,Broken Muni Meter,Out of Order,Street,10037,469 LENOX AVENUE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.813002,-73.941679,"(40.81300196427476, -73.9416785786776)"
94358,35140823,12/31/2016 11:56:24 AM,01/04/2017 02:17:06 AM,HPD,Department of Housing Preservation and Develop...,HEAT/HOT WATER,ENTIRE BUILDING,RESIDENTIAL BUILDING,10039,330 WEST 145 STREET,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.823460,-73.943425,"(40.823460215714306, -73.94342540053778)"
94359,35141568,12/31/2016 11:57:00 AM,01/04/2017 12:00:00 PM,DSNY,"A - Illegal Posting Staten Island, Queens and ...",Dirty Conditions,E15 Illegal Postering,Sidewalk,11201,133 WATER STREET,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.703196,-73.989241,"(40.703196258525494, -73.98924143782365)"
94360,35141380,12/31/2016 11:57:06 AM,02/26/2018 01:00:56 PM,DPR,Department of Parks and Recreation,New Tree Request,For One Address,NaN,10021,35 EAST 76TH STREET,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.774294,-73.962993,"(40.7742936160177, -73.96299262505015)"
94361,35139647,12/31/2016 11:57:11 AM,12/31/2016 03:40:45 PM,NYPD,New York City Police Department,Illegal Parking,Blocked Sidewalk,Street/Sidewalk,10305,233 DONGAN HILLS AVENUE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.585110,-74.094701,"(40.585110055112835, -74.09470093308228)"
94362,35143575,12/31/2016 11:57:20 AM,12/31/2016 01:32:25 PM,NYPD,New York City Police Department,Blocked Driveway,Partial Access,Street/Sidewalk,11238,497 ST JOHNS PLACE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.673316,-73.961599,"(40.67331627208789, -73.96159944172611)"
94363,40790851,12/31/2016 11:57:25 AM,01/03/2017 12:00:00 AM,DOB,Department of Buildings,General Construction/Plumbing,Building Permit - None,NaN,NaN,237 79 STREET,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
94364,35138745,12/31/2016 11:57:53 AM,01/01/2017 01:32:55 PM,NYPD,New York City Police Department,Illegal Parking,Blocked Hydrant,Street/Sidewalk,11385,80-22 64 LANE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.695444,-73.889091,"(40.6954442510181, -73.88909111772713)"
94365,35138766,12/31/2016 11:57:54 AM,12/31/2016 03:43:58 PM,NYPD,New York City Police Department,Derelict Vehicle,With License Plate,Street/Sidewalk,10302,75 TREADWELL AVENUE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.638082,-74.137959,"(40.638082021383546, -74.13795936817937)"
94366,35136984,12/31/2016 11:58:10 AM,12/31/2016 03:41:48 PM,NYPD,New York City Police Department,Noise - Residential,Banging/Pounding,Residential Building/House,11229,2240 BURNETT STREET,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,40.601974,-73.932766,"(40.6019742479744, -73.93276639157727)"

In [2]:
pop_df = pd.read_csv('ACS_16_Pop.csv', header=[1])
income_df = pd.read_csv('ACS_16_Income.csv', header=[1])
rent_df = pd.read_csv('ACS_16_Rent.csv', header=[1])

In [3]:
pop_df.head()

               Id    Id2    Geography  Estimate; Total  Margin of Error; Total
0  8600000US06390   6390  ZCTA5 06390              303                     151
1  8600000US07421   7421  ZCTA5 07421             7281                     512
2  8600000US10001  10001  ZCTA5 10001            23332                    1740
3  8600000US10002  10002  ZCTA5 10002            78096                    2456
4  8600000US10003  10003  ZCTA5 10003            56767                    1934

In [4]:
pop_df = pop_df.drop(columns=['Id', 'Geography', 'Margin of Error; Total'])
pop_df = pop_df.drop(pop_df.index[0])
pop_df = pop_df.drop(pop_df.index[0])
pop_df = pop_df.rename(index=str, columns={'Id2': 'Zip Code', 'Estimate; Total': 'Population Estimate'})

In [5]:
pop_df.head()

   Zip Code  Population Estimate
2     10001                23332
3     10002                78096
4     10003                56767
5     10004                 3044
6     10005                 8710

In [6]:
income_df.head()

,Id,Id2,Geography,Total; Estimate; Households,Total; Margin of Error; Households,Median income (dollars); Estimate; Households,Median income (dollars); Margin of Error; Households,Total; Estimate; Households - One race-- - White,Total; Margin of Error; Households - One race-- - White,Median income (dollars); Estimate; Households - One race-- - White,...,Median income (dollars); Estimate; PERCENT ALLOCATED - Household income in the past 12 months,Median income (dollars); Margin of Error; PERCENT ALLOCATED - Household income in the past 12 months,Total; Estimate; PERCENT ALLOCATED - Family income in the past 12 months,Total; Margin of Error; PERCENT ALLOCATED - Family income in the past 12 months,Median income (dollars); Estimate; PERCENT ALLOCATED - Family income in the past 12 months,Median income (dollars); Margin of Error; PERCENT ALLOCATED - Family income in the past 12 months,Total; Estimate; PERCENT ALLOCATED - Nonfamily income in the past 12 months,Total; Margin of Error; PERCENT ALLOCATED - Nonfamily income in the past 12 months,Median income (dollars); Estimate; PERCENT ALLOCATED - Nonfamily income in the past 12 months,Median income (dollars); Margin of Error; PERCENT ALLOCATED - Nonfamily income in the past 12 months
0,8600000US06390,6390,ZCTA5 06390,118,54,152652,17233,100,22.2,152652,...,(X),(X),63,(X),(X),(X),4.4,(X),(X),(X)
1,8600000US07421,7421,ZCTA5 07421,2575,180,94375,11261,95.5,2.5,96591,...,(X),(X),43.4,(X),(X),(X),31.7,(X),(X),(X)
2,8600000US10001,10001,ZCTA5 10001,11967,548,85168,11872,69.3,3.4,101797,...,(X),(X),31.5,(X),(X),(X),18.4,(X),(X),(X)
3,8600000US10002,10002,ZCTA5 10002,33327,636,35594,2970,37.5,1.8,67933,...,(X),(X),36.1,(X),(X),(X),25.3,(X),(X),(X)
4,8600000US10003,10003,ZCTA5 10003,27258,681,100791,4905,81.9,1.9,102454,...,(X),(X),30.3,(X),(X),(X),21.9,(X),(X),(X)

In [7]:
income_df = income_df.drop(income_df.columns[0], axis=1)
income_df = income_df.drop(income_df.columns[1], axis=1)
income_df = income_df.drop(income_df.columns[1], axis=1)
income_df = income_df.drop(income_df.columns[1], axis=1)
income_df = income_df.drop(income_df.columns[2:120], axis=1)
income_df = income_df.drop(income_df.index[0])
income_df = income_df.drop(income_df.index[0])
income_df = income_df.rename(index=str, columns={'Id2': 'Zip Code', 'Median income (dollars); Estimate; Households': 'Median Estimate'})

In [8]:
income_df.head()

   Zip Code Median Estimate
2     10001           85168
3     10002           35594
4     10003          100791
5     10004          123056
6     10005          130116

In [9]:
rent_df.head()

,Id,Id2,Geography,Estimate; Median gross rent,Margin of Error; Median gross rent
0,8600000US06390,6390,ZCTA5 06390,1388,33
1,8600000US07421,7421,ZCTA5 07421,1772,191
2,8600000US10001,10001,ZCTA5 10001,2114,188
3,8600000US10002,10002,ZCTA5 10002,919,35
4,8600000US10003,10003,ZCTA5 10003,2117,82

In [10]:
rent_df = rent_df.drop(columns=['Id', 'Geography', 'Margin of Error; Median gross rent'])
rent_df = rent_df.drop(rent_df.index[0])
rent_df = rent_df.drop(rent_df.index[0])
rent_df = rent_df.rename(index=str, columns={'Id2': 'Zip Code', 'Estimate; Median gross rent': 'Gross Rent Estimate'})

In [11]:
rent_df.head()

   Zip Code Gross Rent Estimate
2     10001                2114
3     10002                 919
4     10003                2117
5     10004                2911
6     10005                3005

In [18]:
rentandincome = pd.merge(rent_df, income_df, on='Zip Code')
rentandincome

      Zip Code Gross Rent Estimate Median Estimate
0        10001                2114           85168
1        10002                 919           35594
2        10003                2117          100791
3        10004                2911          123056
4        10005                3005          130116
5        10006                2847          125364
6        10007                3339          234958
7        10009                1554           60788
8        10010                2442          110142
9        10011                2029          114134
10       10012                2128          101815
11       10013                1663          104167
12       10014                2337          119026
13       10016                2440          102703
14       10017                2214          106795
15       10018                2849          105479
16       10019                2211           94477
17       10020                   -               -
18       10021                1961          115681
19       10022                2386          123693
20       10023                2256          115080
21       10024                1947          118594
22       10025                1450           80025
23       10026                1045           52082
24       10027                1063           42754
25       10028                2187          111302
26       10029                 911           32500
27       10030                 917           33720
28       10031                1174           41848
29       10032                1131           40054
...        ...                 ...             ...
1763     14865                 604           39132
1764     14867                 854           58411
1765     14869                 565           51597
1766     14870                 880           63376
1767     14871                 783           66575
1768     14872                 638           51293
1769     14873                 553           48770
1770     14874                 856           39231
1771     14877                 622           41250
1772     14878                 730           57404
1773     14879                 680           47083
1774     14880                 664           50726
1775     14881                   -          109803
1776     14882                1253           67236
1777     14883                 713           46354
1778     14884                   -           47917
1779     14885                   -           53636
1780     14886                 852           66661
1781     14889                 819           55375
1782     14891                 677           44161
1783     14892                 686           46125
1784     14893                   -               -
1785     14894                 710           43828
1786     14895                 598           41849
1787     14897                 490           45000
1788     14898                 706           40769
1789     14901                 659           26944
1790     14903                 674           53413
1791     14904                 714           37927
1792     14905                 769           57297

[1793 rows x 3 columns]

In [20]:
data = pd.merge(rentandincome, pop_df, on='Zip Code')
data

      Zip Code Gross Rent Estimate Median Estimate  Population Estimate
0        10001                2114           85168                23332
1        10002                 919           35594                78096
2        10003                2117          100791                56767
3        10004                2911          123056                 3044
4        10005                3005          130116                 8710
5        10006                2847          125364                 3277
6        10007                3339          234958                 6740
7        10009                1554           60788                59799
8        10010                2442          110142                32854
9        10011                2029          114134                50404
10       10012                2128          101815                24536
11       10013                1663          104167                28211
12       10014                2337          119026                31464
13       10016                2440          102703                50444
14       10017                2214          106795                16533
15       10018                2849          105479                 9684
16       10019                2211           94477                39505
17       10020                   -               -                    0
18       10021                1961          115681                45261
19       10022                2386          123693                30262
20       10023                2256          115080                60307
21       10024                1947          118594                58516
22       10025                1450           80025                94717
23       10026                1045           52082                38540
24       10027                1063           42754                64120
25       10028                2187          111302                48205
26       10029                 911           32500                79411
27       10030                 917           33720                30358
28       10031                1174           41848                60778
29       10032                1131           40054                63189
...        ...                 ...             ...                  ...
1763     14865                 604           39132                 3005
1764     14867                 854           58411                 5800
1765     14869                 565           51597                 1359
1766     14870                 880           63376                 9938
1767     14871                 783           66575                 5294
1768     14872                 638           51293                  769
1769     14873                 553           48770                 2662
1770     14874                 856           39231                  255
1771     14877                 622           41250                  372
1772     14878                 730           57404                  603
1773     14879                 680           47083                 1999
1774     14880                 664           50726                 1407
1775     14881                   -          109803                  287
1776     14882                1253           67236                 3985
1777     14883                 713           46354                 3920
1778     14884                   -           47917                  223
1779     14885                   -           53636                  748
1780     14886                 852           66661                 7269
1781     14889                 819           55375                 1779
1782     14891                 677           44161                 4310
1783     14892                 686           46125                 8299
1784     14893                   -               -                    6
1785     14894                 710           43828                 1325
1786     14895                 598           41849                 9446
1787     14897                 490           45000                  846
1788     14898                 706           40769                 1826
1789     14901                 659           26944                16334
1790     14903                 674           53413                 7143
1791     14904                 714           37927                15782
1792     14905                 769           57297                 9150

[1793 rows x 4 columns]